export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const DIARY_ENTRY_PUBLISH_OK = "DIARY_ENTRY_PUBLISH_OK";
export const DIARY_ENTRY_PUBLISH_FAIL = "DIARY_ENTRY_PUBLISH_FAIL";
export const EDITOR_TITLE_CHANGE = "EDITOR_TITLE_CHANGE";
export const EDITOR_CONTENT_CHANGE = "EDITOR_CONTENT_CHANGE";