export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const DIARY_ENTRY_PUBLISH_OK = "DIARY_ENTRY_PUBLISH_OK";
export const DIARY_ENTRY_PUBLISH_FAIL = "DIARY_ENTRY_PUBLISH_FAIL";

export const DIARY_ENTRY_UPDATE_OK = "DIARY_ENTRY_UPDATE_OK";
export const DIARY_ENTRY_UPDATE_FAIl = "DIARY_ENTRY_UPDATE_FAIl";

export const GET_DIARY_ENTRY = "GET_DIARY_ENTRY";
export const GET_DIARY_ENTRY_FAIL = "GET_DIARY_ENTRY_FAIL";

export const DELETE_DIARY_ENTRY_OK = "DELETE_DIARY_ENTRY_OK";
export const DELETE_DIARY_ENTRY_FAIL = "DELETE_DIARY_ENTRY_FAIL";

export const DIARY_ENTRY_SAVE_OK = "DIARY_ENTRY_SAVE_OK";
export const DIARY_ENTRY_SAVE_FAIL = "DIARY_ENTRY_SAVE_FAIL";

export const EDITOR_TITLE_CHANGE = "EDITOR_TITLE_CHANGE";
export const EDITOR_CONTENT_CHANGE = "EDITOR_CONTENT_CHANGE";
export const EDITOR_SET_GUID_ID = "EDITOR_SET_GUID_ID";

export const PUBLISHED_LOADED_SUCCESS = "PUBLISHED_LOADED_SUCCESS";
export const PUBLISHED_LOADED_FAIL = "PUBLISHED_LOADED_FAIL";
export const PUBLISHED_SET = "PUBLISHED_SET";

export const DRAFTS_LOADED_SUCCESS = "DRAFTS_LOADED_SUCCESS";
export const DRAFTS_LOADED_FAIL = "DRAFTS_LOADED_FAIL";
export const DRAFTS_SET = "DRAFTS_SET";